### ISSUE TITLE
broken master

### ISSUE THREAD

**Issue by rasmuserik** [DBCDK/serviceprovider#102]
When running `npm run dev`, current master fail with the error:

   [Error] TypeError: Cannot read property 'bind' of undefined
    at Object.caching (/home/rasmuserik/serviceprovider/node_modules/cache-manager/lib/caching.js:136:30)
    at ClientCache (/home/rasmuserik/serviceprovider/src/provider/lib/ClientCache.js:46:32)
    at initProvider (/home/rasmuserik/serviceprovider/src/ServiceProviderSetup.js:62:105)
    at Object.module.exports.run (/home/rasmuserik/serviceprovider/src/app.js:73:25)

which is likely due to that redis was removed in #99

**Comment by rasmuserik** [comment]
closed by #103
